[workspace]
members = ["."]
resolver = "2"

[package]
name = "hyperion_protocol-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
hyperion_protocol = { path = ".." }

[[bin]]
name = "frame"
path = "fuzz_targets/frame.rs"
test = false
doc = false
bench = false

[[bin]]
name = "handshake"
path = "fuzz_targets/handshake.rs"
test = false
doc = false
bench = false

[[bin]]
name = "status"
path = "fuzz_targets/status.rs"
test = false
doc = false
bench = false

[[bin]]
name = "login"
path = "fuzz_targets/login.rs"
test = false
doc = false
bench = false

[[bin]]
name = "configuration"
path = "fuzz_targets/configuration.rs"
test = false
doc = false
bench = false

[[bin]]
name = "play"
path = "fuzz_targets/play.rs"
test = false
doc = false
bench = false

[[bin]]
name = "nbt"
path = "fuzz_targets/nbt.rs"
test = false
doc = false
bench = false
