[package]
name = "hyperion_world"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Hyperion: chunks, worldgen 1:1, formatos de mundo"

[dependencies]
# Fase 2: se añadirán de la lista blanca (flate2, serde…) + FFI opcional a cubiomes (MIT).